#!/bin/bash -eE
set -o pipefail

function _curl() {
  curl -sf "$@"
}

function _get_config() {
  if [ ! -f $HOME/.config/memos/config.json ]; then
    echo "Please login first."
    return 1
  fi

  cat $HOME/.config/memos/config.json
}

function _finder() {
  if [ ! -z "$FINDER" ]; then
    $FINDER
  elif type peco >/dev/null 2>&1; then
    peco --on-cancel error
  elif type fzf >/dev/null 2>&1; then
    fzf
  else
    echo "Please install fzf or peco."
    return 1
  fi
}

function _usage() {
  cat <<EOF
Usage: $(basename "$0") <subcommand> [<options>]
Options:
  -h, --help                         Print usage
  -v, --verbose                      Print verbose messages
  -t <tag>, --tag <tag>              Tag filter
  -s <content>, --search <content>   Content filter
Subcommands:
  login           Login to the server
  list            List memos
  list_archived   List archived memos
  archive         Archive a memo
  archive <id>    Archive a memo with id
  unarchive       Unarchive a memo
  unarchive <id>  Unarchive a memo with id
  delete          Delete a memo
  delete <id>     Delete a memo with id
  show            Show a memo
  show <id>       Show a memo with id
  edit            Edit a memo (pipe or redirect supported)
  edit <id>       Edit a memo with id (pipe or redirect supported)
  new             Create a new memo (pipe or redirect supported)
EOF
}

function _url_param() {
  for tag in "${tags[@]}"; do
    echo -n "&tag=$(echo -n "$tag" | jq -sRr @uri)"
  done
  for content in "${contents[@]}"; do
    echo -n "&content=$(echo -n "$content" | jq -sRr @uri)"
  done
}

function login() {
  read -p "Server: " server
  read -p "Token: " token
  if [[ $server == */ ]]; then
    server=${server%/}
  fi

  me=$(_curl $server/api/v1/user/me -H "Authorization: Bearer $token")
  echo Logged in as $(echo $me | jq -r .nickname)

  mkdir -p $HOME/.config/memos
  jq -n --arg server "$server" --arg token "$token" \
    '{"server": $server, "token": $token}' >$HOME/.config/memos/config.json
}

function list() {
  server=$(_get_config | jq -r .server)
  token=$(_get_config | jq -r .token)

  if [ $# -eq 0 ]; then
    return 1
  fi
  chain=$1

  list=$(_curl $server/api/v1/memo?$(_url_param) -H "Authorization: Bearer $token")
  id=""
  while [ -z "$id" ]; do
    id=$(echo $list | jq -r '.[] | select(.rowStatus == "NORMAL") | [.id, .content] | @tsv' | _finder | head -n1 | cut -f1)
  done
  $chain $id
}

function list_loop() {
  server=$(_get_config | jq -r .server)
  token=$(_get_config | jq -r .token)

  if [ $# -eq 0 ]; then
    return 1
  fi
  chain=$1

  list=$(_curl $server/api/v1/memo?$(_url_param) -H "Authorization: Bearer $token")
  id=""
  while [ -z "$id" ]; do
    id=$(echo $list | jq -r '.[] | select(.rowStatus == "NORMAL") | [.id, .content] | @tsv' | _finder | head -n1 | cut -f1)
  done

  $chain $id
  list_loop $chain
}

function list_archived() {
  server=$(_get_config | jq -r .server)
  token=$(_get_config | jq -r .token)

  if [ $# -eq 0 ]; then
    return 1
  fi
  chain=$1

  list=$(_curl $server/api/v1/memo?$(_url_param) -H "Authorization: Bearer $token")
  id=$(echo $list | jq -r '.[] | select(.rowStatus == "ARCHIVED") | [.id, .content] | @tsv' | _finder | head -n1 | cut -f1)
  $chain $id
}

function archive() {
  server=$(_get_config | jq -r .server)
  token=$(_get_config | jq -r .token)

  if [ $# -eq 0 ]; then
    list archive
    return 0
  fi
  id=$1

  result=$(_curl $server/api/v1/memo/$id -H "Authorization: Bearer $token" -XPATCH -d '{"rowStatus": "ARCHIVED"}')
  echo "Archived memo $(echo $result | jq -r .id)"
}

function unarchive() {
  server=$(_get_config | jq -r .server)
  token=$(_get_config | jq -r .token)

  if [ $# -eq 0 ]; then
    list_archived unarchive
    return 0
  fi
  id=$1

  result=$(_curl $server/api/v1/memo/$id -H "Authorization: Bearer $token" -XPATCH -d '{"rowStatus": "NORMAL"}')
  echo "Unarchived memo $(echo $result | jq -r .id)"
}

function delete() {
  server=$(_get_config | jq -r .server)
  token=$(_get_config | jq -r .token)

  if [ $# -eq 0 ]; then
    list delete
    return 0
  fi
  id=$1

  _curl $server/api/v1/memo/$id -H "Authorization: Bearer $token" -XDELETE >/dev/null
  echo "Deleted memo $id"
}

function show() {
  server=$(_get_config | jq -r .server)
  token=$(_get_config | jq -r .token)

  if [ $# -eq 0 ]; then
    list show
    return 0
  fi
  id=$1

  body=$(_curl $server/api/v1/memo/$id -H "Authorization: Bearer $token")
  content=$(echo $body | jq -r .content)
  echo "$content"
}

function edit() {
  server=$(_get_config | jq -r .server)
  token=$(_get_config | jq -r .token)

  if [ $# -eq 0 ]; then
    list edit
    return 0
  fi
  id=$1

  if [ -t 0 ]; then
    target=$(mktemp)
    body=$(_curl $server/api/v1/memo/$id -H "Authorization: Bearer $token")
    content=$(echo $body | jq -r .content)
    echo "$content" >$target
    ${EDITOR:-vi} $target
    if diff -q $target <(echo "$content") >/dev/null; then
      echo "No changes."
      return 0
    fi
  elif [ -p /dev/stdin ]; then
    target=/dev/stdin
  elif [ -f /dev/stdin ]; then
    target=/dev/stdin
  else
    echo "Invalid stdin."
    return 1
  fi

  body=$(jq -n --arg content "$(cat $target)" '{"content": $content}')
  result=$(_curl $server/api/v1/memo/$id -H "Authorization: Bearer $token" -XPATCH -d "$body")
  echo "Edited memo $(echo $result | jq -r .id)"

  if [ -t 0 ]; then
    rm $target
  fi
}

function new() {
  server=$(_get_config | jq -r .server)
  token=$(_get_config | jq -r .token)

  if [ -t 0 ]; then
    target=$(mktemp)
    ${EDITOR:-vi} $target
    if [ ! -s $target ]; then
      echo "Empty memo."
      return 1
    fi
  elif [ -p /dev/stdin ]; then
    target=/dev/stdin
  elif [ -f /dev/stdin ]; then
    target=/dev/stdin
  else
    echo "Invalid stdin."
    return 1
  fi

  body=$(jq -n --arg content "$(cat $target)" '{"content": $content}')
  result=$(_curl $server/api/v1/memo -H "Authorization: Bearer $token" -XPOST -d "$body")
  echo "Created memo $(echo $result | jq -r .id)"

  if [ -t 0 ]; then
    rm $target
  fi
}

verbose=0
tags=()
contents=()
commands=()

function parse_args() {
  OPTIND=1
  while getopts ":ht:s:v-:" OPT "$@"; do
    if [ "$OPT" = "-" ]; then
      OPT=${OPTARG%%=*}
      if [ $OPT == $OPTARG ]; then
        OPTARG=${!OPTIND}
      else
        OPTARG=${OPTARG#*=}
      fi
    fi
    case $OPT in
    h | help)
      _usage
      return 0
      ;;
    t)
      tags+=("$OPTARG")
      ;;
    tag)
      tags+=("$OPTARG")
      OPTIND=$((OPTIND + 1))
      ;;
    s)
      contents+=("$OPTARG")
      ;;
    search)
      contents+=("$OPTARG")
      OPTIND=$((OPTIND + 1))
      ;;
    v | verbose)
      verbose=1
      ;;
    *)
      _usage
      return 1
      ;;
    esac
  done
}

function main() {
  while [ $# -gt 0 ]; do
    if [[ $1 == -* ]]; then
      parse_args $@
      shift $((OPTIND - 1))
    else
      commands+=("$1")
      shift
    fi
  done

  if [ $verbose -eq 1 ]; then
    echo "tags: ${tags[@]}"
    echo "contents: ${contents[@]}"
    echo "commands: ${commands[@]}"
    echo "url_param: $(_url_param)"
    set -x
  fi

  case ${commands[0]} in
  login)
    login
    ;;
  list)
    list show
    ;;
  list_archived)
    list_archived show
    ;;
  archive)
    archive ${commands[@]:1}
    ;;
  unarchive)
    unarchive ${commands[@]:1}
    ;;
  delete)
    delete ${commands[@]:1}
    ;;
  show)
    show ${commands[@]:1}
    ;;
  edit)
    edit ${commands[@]:1}
    ;;
  new)
    new
    ;;
  *)
    list_loop edit
    ;;
  esac
}

main $@
